services:
  - type: web
    name: shop-stock-frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    headers:
      - source: /**
        headers:
          - key: Cache-Control
            value: no-store
    routes:
      - type: rewrite
        source: /**
        destination: /index.html
