services:
  - type: web
    name: your-app-name
    buildCommand: npm install && npm run build
    startCommand: npm start
    env: node
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
