services:
  - type: web
    name: shop-stock-frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    env: static
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
